#!/bin/bash

APP=$1
username=$(echo $1 | cut -d "_" -f 1)
PARAM=$2
APPDIR=/home/nap/apps
SERDIR=/home/nap/services
USERSERDIR=$SERDIR/$username/$APP
NAPDIR=/home/nap/nap

[ -d $APPDIR ] || (mkdir $APPDIR)
[ -d $APPDIR/$username ] || (mkdir $APPDIR/$username)

num="$(ls $APPDIR/$username | grep $APP | wc -l)"
num=$[$num+1]

mkdir $APPDIR/$username/${APP}_$num
USERAPPDIR=$APPDIR/$username/${APP}_$num

cp -r $USERSERDIR/* $USERAPPDIR

[ -f $USERAPPDIR/run ] && (sudo rm $USERAPPDIR/run)

argstr="$($NAPDIR/get_parameters_treat $APP)"

if [ -f $USERAPPDIR/mpi.xml ]; then
	context="$(cat $USERAPPDIR/mpi.xml)"
elif [ -f $USERAPPDIR/profile ]; then
	context="$(cat $USERAPPDIR/profile)"
else
	context="$(cat $USERAPPDIR/Dockerfile)"
fi

if [ -z $(echo $PARAM | grep ',') ]; then
	name="{$(echo $argstr | cut -d "," -f 1)}"
	value="$(echo $PARAM | cut -d "," -f 1)"
	newcontext=${context/$name/$value}
else
	i="1"
	while [ ! -z "$(echo $PARAM | cut -d "," -f $i)" ]
	do
		name="{$(echo $argstr | cut -d "," -f $i)}"
       		value="$(echo $PARAM | cut -d "," -f $i)"
        	newcontext=${newcontext/$name/$value}
        	i=$[$i+1]
	done
fi

echo "$newcontext" > $USERAPPDIR/run

if [ -f $USERAPPDIR/mpi.xml ]; then
        mv $USERAPPDIR/run $USERAPPDIR/mpi.xml
elif [ -f $USERAPPDIR/profile ]; then
        mv $USERAPPDIR/run $USERAPPDIR/profile
else
        mv $USERAPPDIR/run $USERAPPDIR/Dockerfile
fi

$NAPDIR/submit_treat ${APP}_$num
