#!/bin/bash

APP=$1
username=$(echo $1 | cut -d "_" -f 1)
PARAM=$2
APPDIR=/home/nap/apps
SERDIR=/home/nap/services
USERSERDIR=$SERDIR/$username/$APP
NAPDIR=/home/nap/nap

[ -d $APPDIR ] || (mkdir $APPDIR)
[ -d $APPDIR/$username ] || (mkdir $APPDIR/$username)

num="$(ls $APPDIR/$username | grep $APP | wc -l)"
num=$[$num+1]

mkdir $APPDIR/$username/${APP}_$num
USERAPPDIR=$APPDIR/$username/${APP}_$num

cp -r $USERSERDIR/* $USERAPPDIR

[ -f $USERAPPDIR/run ] && (sudo rm $USERAPPDIR/run)

argstr="$($NAPDIR/get_parameters_treat $APP)"

context="$(cat $USERAPPDIR/profile)"

i="1"
while [ ! -z "$(echo $PARAM | cut -d "," -f $i)" ]
do
	name="{$(echo $argstr | cut -d "," -f $i)}"
        value="$(echo $PARAM | cut -d "," -f $i)"
       	if [ -z "$newcontext" ]; then
        	newcontext=${context/$name/$value}
        else
        	newcontext=${newcontext/$name/$value}
        fi
        i=$[$i+1]
done

echo "$newcontext" > $USERAPPDIR/run

mv $USERAPPDIR/run $USERAPPDIR/profile

$NAPDIR/submit_treat ${APP}_$num
