#!/bin/bash
set -x

APP=$1
username=$(echo $1 | cut -d "_" -f 1)
PARAM=$2
APPDIR=/home/nap/apps
SERDIR=/home/nap/services
USERSERDIR=$SERDIR/$username/$APP
NAPDIR=/home/nap/nap

[ -d $APPDIR/$username ] || (mkdir $APPDIR/$username)

num="$(ls $APPDIR/$username | grep $APP | wc -l)"
num=$[$num+1]

mkdir $APPDIR/$username/${APP}_$num
USERAPPDIR=$APPDIR/$username/${APP}_$num

cp -r $USERSERDIR/* $USERAPPDIR

sudo rm $USERAPPDIR/run

while read line; do
	key=$(echo $line | cut -f 1 -d ' ')
	if [ "$key" = "command:" ]; then
		i="1"
		argstr="$($NAPDIR/get_parameters_treat $APP)"
		while [ ! -z "$(echo $PARAM | cut -d "," -f $i)" ]
		do
			name="{$(echo $argstr | cut -d "," -f $i)}"
			value="$(echo $PARAM | cut -d "," -f $i)"
			if [ -z "$newline" ]; then
				newline="$(echo ${line/$name/$value} )"
			else
				newline="$(echo ${newline/$name/$value} )"
			fi
			i=$[$i+1]
		done
		echo $newline >> $USERAPPDIR/run
	else
		echo $line >> $USERAPPDIR/run
	fi
done < $USERAPPDIR/profile

mv $USERAPPDIR/run $USERAPPDIR/profile

$NAPDIR/submit_treat ${APP}_$num
