#!/bin/bash

SERDIR=/home/nap/services
APP=$1
APPDIR=/home/nap/apps
username=$(echo $APP | cut -d "_" -f 1)
NAPDIR=/home/nap/nap

if [ -f $SERDIR/$username/$APP/mpi.xml ]; then
	filename="$SERDIR/$username/$APP/mpi.xml"
elif [ -f $SERDIR/$username/$APP/mapreduce.xml ]; then
	filename="$SERDIR/$username/$APP/mapreduce.xml"
elif [ -f $SERDIR/$username/$APP/profile ]; then
	filename="$SERDIR/$username/$APP/profile"
else
	filename="$SERDIR/$username/$APP/Dockerfile"
fi

argstr="$(cat $filename)"

while read line
do
	i="2"
	while [ ! -z "$(echo $line | cut -d "{" -f $i | grep "}")" ]
	do
		arg="$(echo $line | cut -d "{" -f $i | grep "}" | sed "s/}[^}]*//g")"
		if [ ! -z $arg ]; then
			argstr="${argstr}#${arg}"
		fi
		i=$[$i+1]
	done
done < "$filename"

echo $argstr
