#!/bin/bash

SERDIR=/home/nap/services
APP=$1
APPDIR=/home/nap/apps
username=$(echo $APP | cut -d "_" -f 1)
NAPDIR=/home/nap/nap

i="1"
while [ ! -z "$(grep "command:" $SERDIR/$username/$APP/profile | cut -d "{" -f $i)" ]
do
	arg="$(grep "command:" $SERDIR/$username/$1/profile | cut -d "{" -f $i | grep "}" | sed "s/}[^}]*//g")"
	if [ ! -z $arg ]; then
		if [ -z $argstr ]; then
			argstr="$arg"
		else
			argstr="${argstr},${arg}"
		fi
	fi
	i=$[$i+1]
done
if [ -z $argstr ]; then
	[ -d $APPDIR ] || (mkdir $APPDIR)
	[ -d $APPDIR/$username ] || (mkdir $APPDIR/$username)

	num="$(ls $APPDIR/$username | grep $APP | wc -l)"
	num=$[$num+1]

	mkdir $APPDIR/$username/${APP}_$num
	USERAPPDIR=$APPDIR/$username/${APP}_$num
	USERSERDIR=/home/nap/services/$username/$APP

	cp -r $USERSERDIR/* $USERAPPDIR	
	
	$NAPDIR/submit_treat ${APP}_$num

else
	echo $argstr
fi
