#!/bin/bash
USERAPPDIR=/home/nap/apps
NAPDIR=/home/nap/nap
SERDIR=/home/nap/services
args=$*
case $1 in
	#something I did before and will be used after
	git-receive-pack)
		shift 1
		$NAPDIR/git_push_treat $args
	;;

	#submit an app and not deploy it
	submit_app)
		shift 1
		$NAPDIR/submit_treat $*
	;;

	#list-machines
	list-machines)
		fleetctl list-machines
	;;
	
	#deploy 
	deploy_app)
		shift 1
		$NAPDIR/deploy_treat $*	
	;;

	#list services under this user
	list_services)
		[ -d $SERDIR/$2 ] && echo "$(ls $SERDIR/$2)" 
	;;

	#get the url of the service
	get_service_url)
		username=$(echo $2 | cut -d "_" -f 1)
                appname=$(echo $2 | cut -d "_" -f 2)
		echo $(etcdctl get /services/url/$username/$appname)
	;;

	#get instance number of the service
	get_instances_num)
		fleetctl list-units | grep "\<${2}_" | wc -l
	;;

	#list instances of a service
	list_instances)
		fleetctl list-units | grep "\<$2_"
	;;

	#get port of an instance
	get_port)
		username=$(echo $2 | cut -d "_" -f 1)
                appname=$(echo $2 | cut -d "_" -f 2)
		etcdctl get /services/port/$username/$appname
	;;

	#get the journal of an instance
	get_journal)
		fleetctl journal $2
	;;

	#stop an app
	stop_app)
		fleetctl stop $2
	;;

	#start an app
	start_app)
		fleetctl start $2
	;;

	#get the start command of an instance
	cat_app)
		username=$(echo $2 | cut -d "_" -f 1)
		appname=$(echo $2 | cut -d "_" -f 2)
		num=$(echo $2 | cut -d "_" -f 3)
		app="${username}_${appname}_${num}"
		if [ -f $USERAPPDIR/$username/$app/mpi.xml ]; then
			cat $USERAPPDIR/$username/$app/mpi.xml
		elif [ -f $USERAPPDIR/$username/$app/profile ]; then
			cat $USERAPPDIR/$username/$app/profile
		else
			cat $USERAPPDIR/$username/$app/Dockerfile
		fi
	;;

	#get the scheduled parameters in app profile
	get_parameters)
		shift 1
		$NAPDIR/get_parameters_treat $*
	;;

	#start an common app
	start_common)
		shift 1
		$NAPDIR/commonapp_treat $*
	;;

	#start a mpi service
	start_mpi)
		shift 1
		$NAPDIR/mpiapp_treat $*
	;;
	#get images
	get_images)
		username=$(echo $2 | cut -d "_" -f 1)
		docker images | grep $username
	;;
esac
