#!/bin/bash
set -x

APP=$1

username=$(echo $1 | cut -d "_" -f 1)

USERAPPDIR=/home/nop/apps/$username/$APP
NAPDIR=/home/nop/nap

if [ ! -f $USERAPPDIR/Dockerfile ]; then
        if [ -f $USERAPPDIR/pom.xml ]; then
                echo "maven app"
                $NAPDIR/submit_maven_treat $APP
        elif [ -f $USERAPPDIR/mpi.xml ]; then
                echo "mpi app"
                $NAPDIR/submit_mpi_treat $APP
        elif [ -f $USERAPPDIR/profile ]; then
                echo "profile app"
                $NAPDIR/submit_profile_treat $APP
        else
                echo "some other kinds of projects"
        fi
else
        echo "docker file app"
        $NAPDIR/submit_dockerfile_treat $APP
fi
