#!/bin/bash

APP=$1

username=$(echo $1 | cut -d "_" -f 1)

USERAPPDIR=/home/nap/apps/$username/$APP
NAPDIR=/home/nap/nap

if [ ! -f $USERAPPDIR/Dockerfile ]; then
        if [ -f $USERAPPDIR/pom.xml ]; then
                $NAPDIR/submit_maven_treat $APP
	elif [ -f $USERAPPDIR/mapreduce.xml ]; then
		$NAPDIR/submit_mapreduce_treat $APP
        elif [ -f $USERAPPDIR/mpi.xml ]; then
                $NAPDIR/submit_mpi_treat $APP
        elif [ -f $USERAPPDIR/profile ]; then
                $NAPDIR/submit_profile_treat $APP
        else
                echo "some other kinds of projects"
        fi
else
        $NAPDIR/submit_dockerfile_treat $APP
fi
