#!/bin/bash
set -x

APP=$1
username=$(echo $APP | cut -d "_" -f 1)

USERAPPDIR=/home/nop/apps/$username/$APP
NAPDIR=/home/nop/nap
WORKDIR=/etc/systemd/system

touch $USERAPPDIR/Dockerfile
sudo chmod o+w $USERAPPDIR/Dockerfile
touch $USERAPPDIR/run
sudo chmod o+w $USERAPPDIR/run

#look for memory limit and others
#read settings and command in profile
while read line; do
	key=$(echo $line | cut -f 1 -d ' ')
	str=""
	value=$(echo ${line/$key/$str})
	case $key in
		memory:)
			MEMORY=$(echo $line | awk '{ print $2 }')
			DOCKER_OPTS="-m $MEMORY"
		;;
		command:)
			echo $value > $USERAPPDIR/run
		;;
		*)
			echo "other settings"
	esac
done < $USERAPPDIR/profile

#dockerfile for app

cat > $USERAPPDIR/Dockerfile <<EOF
FROM docker.iwanna.xyz:5000/hmonkey/maven
MAINTAINER hmonkey <5681713@qq.com>

COPY run /app/run
COPY data /app/data
WORKDIR /app
ENTRYPOINT ["sh", "run"]
EOF

$NAPDIR/submit_dockerfile_treat $APP "${DOCKER_OPTS}"
